all:
  children:
    web:
      hosts:
        server-one:
          ansible_host: ec2-54-188-156-188.us-west-2.compute.amazonaws.com
        server-two:
          ansible_host: ec2-35-87-145-211.us-west-2.compute.amazonaws.com
